[package]
name = "mcdatapacklint"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
clap = { version = "4.6.7", features = ["derive"] }
hmac = "0.13.0"
reqwest = "0.13.5"
tokio = { version = "1.53.1", features = ["full"] }
tower-http = { version = "0.7.1", features = ["trace"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
